/*
 * Copyright (c) Tile-AI Corporation.
 * Licensed under the MIT License.
 */

/*!
 * \file npu_simt_indirect_load.cc
 * \brief Lower the phase-1 A5 SIMT indirect-load pattern.
 */

#include <tvm/arith/analyzer.h>
#include <tvm/runtime/registry.h>
#include <tvm/tir/expr.h>
#include <tvm/tir/op.h>
#include <tvm/tir/stmt.h>
#include <tvm/tir/stmt_functor.h>
#include <tvm/tir/transform.h>

#include <cstdlib>
#include <iostream>
#include <string>

namespace tvm {
namespace tl {

using namespace tir;

namespace {

constexpr const char *kFeature = "A5 SIMT indirect load phase 1";

enum class IndirectLoadKind {
  kRank1,
  kLutRow2D,
};

struct IndirectLoadPattern {
  const BufferLoadNode *src_load{nullptr};
  const BufferLoadNode *idx_load{nullptr};
  Buffer dst_buffer;
  PrimExpr valid_extent;
  IndirectLoadKind kind{IndirectLoadKind::kRank1};
  PrimExpr src_row;
  PrimExpr idx_row;
  PrimExpr idx_lane_base;
};

bool IsSharedScope(const Buffer &buffer) {
  return buffer.scope() == "shared" || buffer.scope() == "shared.dyn";
}

bool SameExpr(const PrimExpr &lhs, const PrimExpr &rhs) {
  return StructuralEqual()(lhs, rhs);
}

PrimExpr MakeRegion(Buffer buffer, PrimExpr offset, int access_mask,
                    PrimExpr extent) {
  Op region_op = Op::Get("tl.region");
  PrimExpr load = BufferLoad(buffer, {offset});
  Array<PrimExpr> args = {load, make_const(DataType::Int(32), access_mask),
                          extent};
  return Call(DataType::Handle(), region_op, args);
}

PrimExpr MakeRegion2D(Buffer buffer, PrimExpr offset0, PrimExpr offset1,
                      int access_mask, PrimExpr extent0, PrimExpr extent1) {
  Op region_op = Op::Get("tl.region");
  PrimExpr load = BufferLoad(buffer, {offset0, offset1});
  Array<PrimExpr> args = {load, make_const(DataType::Int(32), access_mask),
                          extent0, extent1};
  return Call(DataType::Handle(), region_op, args);
}

bool SimtDebugEnabled() {
  const char *value = std::getenv("TILELANG_SIMT_DUMP_TIR");
  if (value == nullptr) {
    return false;
  }
  std::string normalized(value);
  return !(normalized.empty() || normalized == "0" || normalized == "false" ||
           normalized == "False" || normalized == "FALSE");
}

void DebugDumpStmt(const std::string &label, const Stmt &stmt) {
  if (!SimtDebugEnabled()) {
    return;
  }
  std::cerr << "[NpuSimtIndirectLoad] " << label << ":\n"
            << stmt << "\n";
}

bool MatchLaneIndex(const PrimExpr &expr, const Var &loop_var,
                    PrimExpr *base) {
  // 匹配 index 的 lane 维。TIR 对象树里 `CODES[s, m]`
  // 的第二维不是字符串 "m"，而是一个 PrimExpr；这里判断它是否
  // 等价于当前 T.Parallel 的 loop_var，或者是 base + loop_var。
  // 匹配成功后，base 用来描述这一行 index tensor 的起始列偏移。
  if (SameExpr(expr, loop_var)) {
    *base = make_zero(loop_var.dtype());
    return true;
  }

  const auto *add = expr.as<AddNode>();
  if (!add) {
    return false;
  }
  if (SameExpr(add->a, loop_var)) {
    *base = add->b;
    return true;
  }
  if (SameExpr(add->b, loop_var)) {
    *base = add->a;
    return true;
  }
  return false;
}

PrimExpr MatchTailMask(PrimExpr condition, const Var &loop_var) {
  // Accept the two tail forms generated by TileLang today:
  //   if i < valid
  //   if start + i < N
  // Both lower to a per-block valid lane count consumed by the backend mask.
  // 这里处理的是 IfThenElseNode 的 condition 子树，把逐 lane 的边界判断
  // 归约成一个 valid_extent，后续 codegen 再用 lanes < valid_extent 生成 mask。
  const auto *lt = condition.as<LTNode>();
  if (!lt) {
    return PrimExpr();
  }
  if (SameExpr(lt->a, loop_var)) {
    return lt->b;
  }

  const auto *add = lt->a.as<AddNode>();
  if (!add) {
    return PrimExpr();
  }
  if (SameExpr(add->a, loop_var)) {
    return lt->b - add->b;
  }
  if (SameExpr(add->b, loop_var)) {
    return lt->b - add->a;
  }
  return PrimExpr();
}

bool MatchStoreBody(const Stmt &stmt, const Var &loop_var,
                    IndirectLoadPattern *pattern) {
  // Phase 1 deliberately matches only the canonical indirect-load store:
  //   O_UB[i] = X[IDX_UB[i]]
  // Other arithmetic around the result should be expressed in later statements.
  //
  // 这个函数是对象树匹配的核心。它看到的 stmt 已经是 TVM TIR 节点，
  // 不是 Python 字符串，也不是 Python AST。一个 kernel 语句：
  //
  //   O_UB[m] = LUT_shared[s, CODES[s, m]]
  //
  // 在这里大致表现为：
  //
  //   BufferStore(
  //     buffer = O_UB,
  //     indices = [m],
  //     value = BufferLoad(
  //       buffer = LUT_shared,
  //       indices = [s, BufferLoad(CODES, [s, m])]
  //     )
  //   )
  //
  // 所以下面的判断都是在沿着 BufferStore / BufferLoad 对象树向下拆。
  const auto *store = stmt.as<BufferStoreNode>();
  if (!store || store->indices.size() != 1U) {
    return false;
  }
  if (!SameExpr(store->indices[0], loop_var)) {
    return false;
  }

  const auto *src_load = store->value.as<BufferLoadNode>();
  if (!src_load) {
    return false;
  }

  if (src_load->indices.size() == 1U) {
    // 1D 原始模式：
    //
    //   O_UB[i] = X[IDX_UB[i]]
    //
    // 对象树要求 RHS 是一个 1D BufferLoad，且它的唯一 index
    // 也是一个 1D BufferLoad，并且 index 的下标就是当前 loop_var。
    const auto *idx_load = src_load->indices[0].as<BufferLoadNode>();
    if (!idx_load || idx_load->indices.size() != 1U) {
      return false;
    }
    if (!SameExpr(idx_load->indices[0], loop_var)) {
      return false;
    }

    pattern->src_load = src_load;
    pattern->idx_load = idx_load;
    pattern->dst_buffer = store->buffer;
    pattern->kind = IndirectLoadKind::kRank1;
    return true;
  }

  // Minimal 2D LUT-row pattern:
  //   O_UB[m] = LUT_SHARED[s, CODES[s, m]]
  // The row dimension is carried as a scalar base offset; lanes are still the
  // inner T.Parallel axis and the code tensor slice is CODES[s, 0:block].
  //
  // 2D 简化实验模式：
  //
  //   O_UB[m] = LUT_SHARED[s, CODES[s, m]]
  //
  // 这里的 2D 指 source/index 的访问形态是二维：
  //   - source 是 LUT_SHARED[s, code]
  //   - index tensor 是 CODES[s, m]
  //
  // 当前版本要求 source 第一维和 index 第一维是同一个表达式 s。
  // 这样后续 BuildIndirectLoad 可以把 source region 描述成
  // `LUT_SHARED[s, 0:K]`，把 index region 描述成 `CODES[s, 0:block]`。
  // dst 仍然是 1D 的 O_UB[m]，所以这还不是一次性 SxM 的 2D HFusion op。
  if (src_load->indices.size() != 2U) {
    return false;
  }
  const auto *idx_load = src_load->indices[1].as<BufferLoadNode>();
  if (!idx_load || idx_load->indices.size() != 2U) {
    return false;
  }
  if (!SameExpr(src_load->indices[0], idx_load->indices[0])) {
    return false;
  }
  PrimExpr lane_base;
  if (!MatchLaneIndex(idx_load->indices[1], loop_var, &lane_base)) {
    return false;
  }

  pattern->src_load = src_load;
  pattern->idx_load = idx_load;
  pattern->dst_buffer = store->buffer;
  pattern->kind = IndirectLoadKind::kLutRow2D;
  pattern->src_row = src_load->indices[0];
  pattern->idx_row = idx_load->indices[0];
  pattern->idx_lane_base = lane_base;
  return true;
}

class NpuSimtIndirectLoadRewriter : public StmtMutator {
 public:
  Stmt VisitStmt_(const ForNode *op) final {
    if (op->kind != ForKind::kParallel) {
      return StmtMutator::VisitStmt_(op);
    }

    // StmtMutator 遍历到每一个 ForNode 时都会进入这里。打开
    // TILELANG_SIMT_DUMP_TIR=1 后，先无条件打印当前 T.Parallel 的对象树；
    // 后续无论匹配成功还是失败，都能看到 pass 实际处理过哪些 loop。
    DebugDumpStmt("visit T.Parallel", GetRef<For>(op));

    Optional<Stmt> rewritten = TryRewrite(op);
    if (rewritten.defined()) {
      return rewritten.value();
    }
    return StmtMutator::VisitStmt_(op);
  }

 private:
  Optional<Stmt> TryRewrite(const ForNode *op) {
    PrimExpr valid_extent = op->extent;
    Stmt body = op->body;

    // Unsupported T.Parallel forms are left untouched so the regular NPUIR
    // vectorization path can still handle them.
    //
    // 输入必须是 T.Parallel 对应的 ForNode。这里先剥掉可支持的尾块 if：
    //
    //   for m in T.Parallel(block):
    //     if m < valid:
    //       O_UB[m] = ...
    //
    // 剥离后 body 应该只剩一个 BufferStoreNode；如果还有 else、
    // 复杂语句序列、或者 condition 不是可归约的 tail mask，就不改写。
    if (const auto *if_node = op->body.as<IfThenElseNode>()) {
      if (if_node->else_case.defined()) {
        return NullOpt;
      }
      valid_extent = MatchTailMask(if_node->condition, op->loop_var);
      if (!valid_extent.defined()) {
        return NullOpt;
      }
      body = if_node->then_case;
    }

    IndirectLoadPattern pattern;
    // 在剥离 tail mask 后的 body 上做真正的对象树匹配。
    // 匹配成功时，pattern 中会保存 source load、index load、dst buffer、
    // 模式类型以及 2D 模式需要的行号/列偏移等信息。
    if (!MatchStoreBody(body, op->loop_var, &pattern)) {
      return NullOpt;
    }
    pattern.valid_extent = valid_extent;

    // 这里是保守边界检查。检查失败不报错，只返回 NullOpt，
    // 让原始 T.Parallel 保留给后面的 NpuLoopVectorize 或其他 pass。
    if (!CanRewriteBoundary(op, pattern)) {
      return NullOpt;
    }
    Stmt rewritten = BuildIndirectLoad(op, pattern);
    DebugDumpStmt("rewritten TIR", rewritten);
    return rewritten;
  }

  bool CanRewriteBoundary(const ForNode *op,
                          const IndirectLoadPattern &pattern) {
    // Boundary misses are not errors at this TIR stage. Leave the original
    // loop intact so NpuLoopVectorize can still handle the SIMD path.
    const auto *extent = op->extent.as<IntImmNode>();
    if (!extent || extent->value <= 0 || !is_zero(op->min)) {
      return false;
    }
    if (!pattern.valid_extent.dtype().is_int() &&
        !pattern.valid_extent.dtype().is_uint()) {
      return false;
    }

    if (pattern.kind == IndirectLoadKind::kRank1) {
      if (pattern.src_load->buffer.scope() != "global") {
        return false;
      }
      if (!IsSharedScope(pattern.idx_load->buffer) ||
          !IsSharedScope(pattern.dst_buffer)) {
        return false;
      }
    } else {
      if (pattern.src_load->buffer.scope() != "global" &&
          !IsSharedScope(pattern.src_load->buffer)) {
        return false;
      }
      if (pattern.idx_load->buffer.scope() != "global" &&
          !IsSharedScope(pattern.idx_load->buffer)) {
        return false;
      }
      if (!IsSharedScope(pattern.dst_buffer)) {
        return false;
      }
    }

    if (pattern.src_load->buffer->dtype != DataType::Float(32)) {
      return false;
    }
    if (pattern.idx_load->buffer->dtype != DataType::Int(32)) {
      return false;
    }
    return pattern.dst_buffer->dtype == pattern.src_load->buffer->dtype;
  }

  Stmt BuildIndirectLoad(const ForNode *op,
                         const IndirectLoadPattern &pattern) {
    PrimExpr zero = make_zero(op->loop_var.dtype());
    PrimExpr block = op->extent;

    // The replacement is an internal TileLang op. Developer-mode codegen lowers
    // it to the backend-recognized triton_indirect_load call.
    //
    // 这里把匹配出的对象树重新编码成 TileLang 内部 op：
    //
    //   Evaluate(Call("tl.npuir_indirect_load", ...))
    //
    // 它仍然是 TIR 对象树的一部分。后续 `src/op/ascend.cc`
    // 解析这些 tl.region 参数，`codegen_npuir_dev.cc` 再把它降成
    // `call @triton_indirect_load(...)`。
    PrimExpr src_region;
    PrimExpr idx_region;
    if (pattern.kind == IndirectLoadKind::kRank1) {
      // 1D 模式参数：
      //   src: X[0:1]，真实离散位置由 indices 给出
      //   idx: IDX_UB[0:block]
      //   dst: O_UB[0:block]
      src_region = MakeRegion(pattern.src_load->buffer, zero, 1,
                              make_const(DataType::Int(32), 1));
      idx_region = MakeRegion(pattern.idx_load->buffer, zero, 1, block);
    } else {
      // 2D LUT-row 模式参数：
      //   src: LUT_SHARED[s, 0:K]
      //   idx: CODES[s, lane_base : lane_base + block]
      //   dst: O_UB[0:block]
      //
      // 注意：这里传给 npuir_indirect_load 的 src/index region 是二维 region，
      // 但 dst 仍是一维 region。当前 codegen 会把 LUT 行基址折到 offset 里。
      src_region = MakeRegion2D(
          pattern.src_load->buffer, pattern.src_row, zero, 1,
          make_const(DataType::Int(32), 1), pattern.src_load->buffer->shape[1]);
      idx_region = MakeRegion2D(
          pattern.idx_load->buffer, pattern.idx_row, pattern.idx_lane_base, 1,
          make_const(DataType::Int(32), 1), block);
    }
    PrimExpr dst_region = MakeRegion(pattern.dst_buffer, zero, 2, block);

    Op indirect_load_op = Op::Get("tl.npuir_indirect_load");
    Array<PrimExpr> args = {src_region, idx_region, dst_region,
                            pattern.valid_extent};
    PrimExpr call = Call(DataType::Void(), indirect_load_op, args);
    return Evaluate(call);
  }
};

}  // namespace

using namespace tir::transform;

tvm::transform::Pass NpuSimtIndirectLoad() {
  auto pass_func = [=](PrimFunc f, IRModule m, PassContext ctx) {
    // This pass must run before NpuLoopVectorize, otherwise the canonical
    // T.Parallel form is already converted into the SIMD loop representation.
    auto *new_pf = f.CopyOnWrite();
    new_pf->body = NpuSimtIndirectLoadRewriter()(std::move(new_pf->body));
    return f;
  };
  return CreatePrimFuncPass(pass_func, 0, "tl.NpuSimtIndirectLoad", {});
}

TVM_REGISTER_GLOBAL("tl.transform.NpuSimtIndirectLoad")
    .set_body_typed(NpuSimtIndirectLoad);

}  // namespace tl
}  // namespace tvm
